# Generated by Django 5.0.6 on 2024-06-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_project_alter_user_username_projectbulletpoint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursework',
            name='display',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='education',
            name='display',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='importantlink',
            name='display',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='display',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectbulletpoint',
            name='display',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='display_contact_info',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='display',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='marks',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='contact_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='full_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
