# Generated by Django 5.0.6 on 2024-06-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_coursework_display_education_display_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursework',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='importantlink',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='projectbulletpoint',
            name='point',
            field=models.TextField(blank=True, null=True),
        ),
    ]
