# Generated by Django 5.0.6 on 2024-06-18 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_importantlink_link_name_resume_email_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('link_name', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('subheading', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('display', models.BooleanField(default=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='api.resume')),
            ],
        ),
    ]
