# Generated by Django 5.0.6 on 2024-06-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_customfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='email_user',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
